'use client';

/**
 * First-time onboarding tour.
 *
 * Behaviour:
 *  - Shows once per browser, persisted via `mm_onboarded_v1` localStorage key.
 *  - Five short slides explaining the game flow (welcome → difficulty → case file
 *    → interrogation → verdict).
 *  - User can skip at any time; completing the last slide also marks it done.
 *  - Mounts on /dashboard; the modal sits above all content with a soft backdrop.
 *
 * Design language matches the rest of the noir UI — `aged-paper` panel, gold
 * accents, mono headings, framer-motion staggered transitions.
 */

import React, { useEffect, useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Fingerprint,
  FolderSearch,
  ScrollText,
  MessageCircleQuestion,
  Gavel,
  X as XIcon,
  ArrowRight,
  ArrowLeft,
} from 'lucide-react';

const STORAGE_KEY = 'mm_onboarded_v1';

interface Slide {
  icon: React.ComponentType<{ size?: number; className?: string }>;
  eyebrow: string;
  title: string;
  body: string;
}

const SLIDES: Slide[] = [
  {
    icon: Fingerprint,
    eyebrow: '01 / Welcome, Detective',
    title: 'Every case is unique.',
    body:
      'Each murder mystery is generated by AI on the fly — a one-of-a-kind victim, suspects, and culprit. No two cases are ever the same.',
  },
  {
    icon: FolderSearch,
    eyebrow: '02 / Pick your difficulty',
    title: 'Three suspects or six?',
    body:
      'Easy cases have glaring contradictions. Hard cases bury the truth under red herrings. Each tier costs coins up front and rewards you for solving it.',
  },
  {
    icon: ScrollText,
    eyebrow: '03 / Read the case file',
    title: 'The dossier hides everything.',
    body:
      'Open the file. Study the victim, the crime scene, the alibis. The narrator will read it aloud — every clue is a thread worth pulling.',
  },
  {
    icon: MessageCircleQuestion,
    eyebrow: '04 / Interrogate suspects',
    title: 'Press them until they crack.',
    body:
      'Talk to suspects and witnesses. Type or use your microphone. Listen for contradictions — the AI will let truth slip if you push the right way.',
  },
  {
    icon: Gavel,
    eyebrow: '05 / Name the killer',
    title: 'One accusation. Make it count.',
    body:
      'When you’re ready, hit Make Accusation. Get it right and the city sleeps easier. Get it wrong, or run out of time, and the killer walks.',
  },
];

const EASE = [0.16, 1, 0.3, 1] as [number, number, number, number];

export function OnboardingTour() {
  const [isOpen, setIsOpen] = useState(false);
  const [step, setStep] = useState(0);

  // Show once on first visit. Defer mounting until after the dashboard renders
  // so the modal feels like a deliberate welcome, not a page-load blocker.
  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      const seen = localStorage.getItem(STORAGE_KEY);
      if (!seen) {
        const t = setTimeout(() => setIsOpen(true), 650);
        return () => clearTimeout(t);
      }
    } catch {
      // localStorage unavailable (private browsing) — just skip the tour.
    }
  }, []);

  const close = useCallback(() => {
    try {
      localStorage.setItem(STORAGE_KEY, '1');
    } catch {}
    setIsOpen(false);
  }, []);

  const next = useCallback(() => {
    if (step < SLIDES.length - 1) setStep((s) => s + 1);
    else close();
  }, [step, close]);

  const prev = useCallback(() => {
    if (step > 0) setStep((s) => s - 1);
  }, [step]);

  const slide = SLIDES[step];
  const Icon = slide.icon;

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          key="onboarding-backdrop"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.4, ease: EASE }}
          className="fixed inset-0 z-[100] flex items-center justify-center px-4"
          style={{
            background: 'rgba(4,4,6,0.78)',
            backdropFilter: 'blur(10px)',
            WebkitBackdropFilter: 'blur(10px)',
          }}
          role="dialog"
          aria-modal="true"
          aria-label="Welcome tour"
        >
          <motion.div
            key="onboarding-card"
            initial={{ opacity: 0, y: 24, scale: 0.96, filter: 'blur(8px)' }}
            animate={{ opacity: 1, y: 0, scale: 1, filter: 'blur(0px)' }}
            exit={{ opacity: 0, y: -10, scale: 0.97 }}
            transition={{ duration: 0.55, ease: EASE }}
            className="relative w-full max-w-lg aged-paper rounded-2xl border border-border-bright/30 shadow-[0_30px_80px_-20px_rgba(0,0,0,0.7)]"
          >
            {/* Skip / close */}
            <button
              onClick={close}
              aria-label="Skip tour"
              className="absolute top-3 right-3 p-1.5 rounded-md transition-all"
              style={{ color: 'rgba(237,230,214,0.45)' }}
              onMouseEnter={(e) => {
                (e.currentTarget as HTMLButtonElement).style.color = '#e8c84a';
              }}
              onMouseLeave={(e) => {
                (e.currentTarget as HTMLButtonElement).style.color = 'rgba(237,230,214,0.45)';
              }}
            >
              <XIcon size={16} />
            </button>

            <div className="p-6 sm:p-8 flex flex-col gap-5">
              {/* Step counter */}
              <div className="flex items-center gap-1.5">
                {SLIDES.map((_, i) => (
                  <motion.span
                    key={i}
                    layout
                    className="h-1 rounded-full transition-all"
                    style={{
                      width: i === step ? 24 : 8,
                      background:
                        i === step
                          ? '#c9a227'
                          : i < step
                          ? 'rgba(201,162,39,0.45)'
                          : 'rgba(237,230,214,0.18)',
                    }}
                    transition={{ duration: 0.4, ease: EASE }}
                  />
                ))}
              </div>

              {/* Slide body — animated on step change */}
              <AnimatePresence mode="wait">
                <motion.div
                  key={step}
                  initial={{ opacity: 0, y: 12, filter: 'blur(6px)' }}
                  animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
                  exit={{ opacity: 0, y: -8, filter: 'blur(4px)' }}
                  transition={{ duration: 0.45, ease: EASE }}
                  className="flex flex-col gap-4 min-h-[210px]"
                >
                  {/* Icon */}
                  <div className="w-12 h-12 rounded-xl border border-accent/35 flex items-center justify-center bg-accent/8">
                    <Icon size={22} className="text-accent" />
                  </div>

                  {/* Eyebrow */}
                  <p className="font-mono text-[10px] tracking-[0.45em] uppercase text-accent/65">
                    {slide.eyebrow}
                  </p>

                  {/* Title */}
                  <h3 className="font-display text-2xl sm:text-3xl font-black text-foreground leading-tight tracking-tight">
                    {slide.title}
                  </h3>

                  {/* Body */}
                  <p className="font-serif text-foreground-dim text-[15px] leading-relaxed">
                    {slide.body}
                  </p>
                </motion.div>
              </AnimatePresence>

              {/* Footer */}
              <div className="flex items-center justify-between pt-3 border-t border-border-bright/20">
                <button
                  onClick={close}
                  className="font-mono text-[11px] tracking-[0.3em] uppercase text-muted/55 hover:text-foreground/90 transition-colors"
                >
                  Skip tour
                </button>

                <div className="flex items-center gap-2">
                  {step > 0 && (
                    <button
                      onClick={prev}
                      className="flex items-center gap-1.5 font-mono text-[11px] tracking-widest uppercase px-3 py-2 rounded-md text-foreground/70 border border-border-bright/30 hover:border-accent/50 hover:text-foreground transition-all"
                    >
                      <ArrowLeft size={12} />
                      Back
                    </button>
                  )}
                  <motion.button
                    onClick={next}
                    whileHover={{ scale: 1.03 }}
                    whileTap={{ scale: 0.97 }}
                    transition={{ type: 'spring', stiffness: 400, damping: 22 }}
                    className="flex items-center gap-2 font-bold text-[12px] tracking-[0.18em] uppercase px-4 py-2 rounded-md bg-accent text-background border border-accent/80 hover:bg-accent-hover hover:shadow-gold-sm transition-all"
                  >
                    {step === SLIDES.length - 1 ? 'Begin Investigating' : 'Next'}
                    <ArrowRight size={13} />
                  </motion.button>
                </div>
              </div>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
